# Generated by Django 5.2.2 on 2025-10-20 17:59

import django.core.validators
import money_tracker.currencies.mixins
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount_lcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ratio', models.DecimalField(decimal_places=2, default=0.3, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
            ],
            options={
                'verbose_name_plural': 'Equities',
                'ordering': ['id'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
            bases=(models.Model, money_tracker.currencies.mixins.CurrencyConversionMixin),
        ),
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount_lcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Investment Accounts',
                'ordering': ['id'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
            bases=(models.Model, money_tracker.currencies.mixins.CurrencyConversionMixin),
        ),
        migrations.CreateModel(
            name='LiquidAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount_lcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Liquid Assets',
                'ordering': ['id'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
            bases=(models.Model, money_tracker.currencies.mixins.CurrencyConversionMixin),
        ),
        migrations.CreateModel(
            name='RetirementAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount_lcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('employer', models.CharField(blank=True, max_length=65, null=True)),
            ],
            options={
                'verbose_name_plural': 'Retirement Accounts',
                'ordering': ['id'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
            bases=(models.Model, money_tracker.currencies.mixins.CurrencyConversionMixin),
        ),
    ]
