# Generated by Django 5.2.2 on 2025-10-20 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equity',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='equity',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidasset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidasset',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='liquidasset',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retirementaccount',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retirementaccount',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='retirementaccount',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
