# Generated by Django 5.0.11 on 2025-03-01 18:39

import django.db.models.deletion
import money_tracker.expenses.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0004_alter_exchangerate_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscretionaryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount_lcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_currency', to='currencies.currency')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'get_latest_by': ['-created_at'],
                'abstract': False,
            },
            bases=(models.Model, money_tracker.expenses.mixins.CurrencyConversionMixin),
        ),
        migrations.CreateModel(
            name='FixedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount_lcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_currency', to='currencies.currency')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'get_latest_by': ['-created_at'],
                'abstract': False,
            },
            bases=(models.Model, money_tracker.expenses.mixins.CurrencyConversionMixin),
        ),
        migrations.CreateModel(
            name='VariableExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount_lcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_currency', to='currencies.currency')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'get_latest_by': ['-created_at'],
                'abstract': False,
            },
            bases=(models.Model, money_tracker.expenses.mixins.CurrencyConversionMixin),
        ),
    ]
