# Generated by Django 5.0.11 on 2025-03-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discretionaryexpense',
            options={'verbose_name': 'Discretionary Expense', 'verbose_name_plural': 'Discretionary Expenses'},
        ),
        migrations.AlterModelOptions(
            name='fixedexpense',
            options={'verbose_name': 'Fixed Expense', 'verbose_name_plural': 'Fixed Expenses'},
        ),
        migrations.AlterModelOptions(
            name='variableexpense',
            options={'verbose_name': 'Variable Expense', 'verbose_name_plural': 'Variable Expenses'},
        ),
    ]
