# Generated by Django 5.2.2 on 2025-07-06 11:21

import django.db.models.deletion
import money_tracker.currencies.mixins
import money_tracker.liabilities.mixins
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestType',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itcreator', related_query_name='itcreator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itmodifier', related_query_name='itmodifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interest Type',
                'verbose_name_plural': 'Interest Types',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('loan_date', models.DateField()),
                ('amount_taken', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount_taken_lcy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('reason', models.TextField()),
                ('compound_frequency', models.IntegerField(blank=True, default=0, null=True)),
                ('repayment_date', models.DateField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('12.50'), help_text='Annual interest rate in percentage.', max_digits=4)),
                ('interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20)),
                ('interest_lcy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20)),
                ('in_default', models.BooleanField(default=False)),
                ('amount_repay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('amount_repay_lcy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('amount_paid_lcy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('due_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('due_balance_lcy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lcreator', related_query_name='lcreator', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lcurrency', related_query_name='lcurrency', to='currencies.currency')),
                ('interest_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linterest', related_query_name='linterest', to='liabilities.interesttype')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lmodifier', related_query_name='lmodifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'get_latest_by': 'created_at',
            },
            bases=(models.Model, money_tracker.currencies.mixins.CurrencyConversionMixin, money_tracker.liabilities.mixins.InterestCalculationMixin),
        ),
    ]
