# Generated by Django 5.2.2 on 2025-07-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='compound_frequency',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
