# Generated by Django 5.2.2 on 2025-10-20 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0002_initial'),
        ('liabilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interesttype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itcreator', related_query_name='itcreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interesttype',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itmodifier', related_query_name='itmodifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lcreator', related_query_name='lcreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lcurrency', related_query_name='lcurrency', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linterest', related_query_name='linterest', to='liabilities.interesttype'),
        ),
        migrations.AddField(
            model_name='loan',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lmodifier', related_query_name='lmodifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
