# Generated by Django 5.2.2 on 2025-07-05 16:55

import django.db.models.deletion
import money_tracker.currencies.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarnedIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_lcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', related_query_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', related_query_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Earned Income',
                'verbose_name_plural': 'Earned Income',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['income_name'], name='income_earn_income__05cd97_idx'), models.Index(fields=['created_at'], name='income_earn_created_00ace9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='earnedincome_amount_gte_zero'), models.CheckConstraint(condition=models.Q(('amount_lcy__gte', 0)), name='earnedincome_amount_lcy_gte_zero')],
            },
            bases=(models.Model, money_tracker.currencies.mixins.CurrencyConversionMixin),
        ),
        migrations.CreateModel(
            name='PassiveIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_lcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', related_query_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', related_query_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passive Income',
                'verbose_name_plural': 'Passive Income',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['income_name'], name='income_pass_income__30a92b_idx'), models.Index(fields=['created_at'], name='income_pass_created_924415_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='passiveincome_amount_gte_zero'), models.CheckConstraint(condition=models.Q(('amount_lcy__gte', 0)), name='passiveincome_amount_lcy_gte_zero')],
            },
            bases=(models.Model, money_tracker.currencies.mixins.CurrencyConversionMixin),
        ),
        migrations.CreateModel(
            name='PortfolioIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_lcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', related_query_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', related_query_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Income',
                'verbose_name_plural': 'Portfolio Income',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['income_name'], name='income_port_income__1f0330_idx'), models.Index(fields=['created_at'], name='income_port_created_c2ba99_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='portfolioincome_amount_gte_zero'), models.CheckConstraint(condition=models.Q(('amount_lcy__gte', 0)), name='portfolioincome_amount_lcy_gte_zero')],
            },
            bases=(models.Model, money_tracker.currencies.mixins.CurrencyConversionMixin),
        ),
    ]
