# Generated by Django 5.2.2 on 2025-10-20 17:59

import money_tracker.currencies.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarnedIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_lcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Earned Income',
                'verbose_name_plural': 'Earned Income',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
                'abstract': False,
            },
            bases=(models.Model, money_tracker.currencies.mixins.CurrencyConversionMixin),
        ),
        migrations.CreateModel(
            name='PassiveIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_lcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Passive Income',
                'verbose_name_plural': 'Passive Income',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
                'abstract': False,
            },
            bases=(models.Model, money_tracker.currencies.mixins.CurrencyConversionMixin),
        ),
        migrations.CreateModel(
            name='PortfolioIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_lcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Income',
                'verbose_name_plural': 'Portfolio Income',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
                'abstract': False,
            },
            bases=(models.Model, money_tracker.currencies.mixins.CurrencyConversionMixin),
        ),
    ]
