# Generated by Django 5.2.2 on 2025-10-20 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0002_initial'),
        ('income', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='earnedincome',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', related_query_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='earnedincome',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='earnedincome',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', related_query_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passiveincome',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', related_query_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passiveincome',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='passiveincome',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', related_query_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolioincome',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', related_query_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolioincome',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='portfolioincome',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', related_query_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='earnedincome',
            index=models.Index(fields=['income_name'], name='income_earn_income__05cd97_idx'),
        ),
        migrations.AddIndex(
            model_name='earnedincome',
            index=models.Index(fields=['created_at'], name='income_earn_created_00ace9_idx'),
        ),
        migrations.AddConstraint(
            model_name='earnedincome',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='earnedincome_amount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='earnedincome',
            constraint=models.CheckConstraint(condition=models.Q(('amount_lcy__gte', 0)), name='earnedincome_amount_lcy_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='passiveincome',
            index=models.Index(fields=['income_name'], name='income_pass_income__30a92b_idx'),
        ),
        migrations.AddIndex(
            model_name='passiveincome',
            index=models.Index(fields=['created_at'], name='income_pass_created_924415_idx'),
        ),
        migrations.AddConstraint(
            model_name='passiveincome',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='passiveincome_amount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='passiveincome',
            constraint=models.CheckConstraint(condition=models.Q(('amount_lcy__gte', 0)), name='passiveincome_amount_lcy_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='portfolioincome',
            index=models.Index(fields=['income_name'], name='income_port_income__1f0330_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioincome',
            index=models.Index(fields=['created_at'], name='income_port_created_c2ba99_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfolioincome',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='portfolioincome_amount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='portfolioincome',
            constraint=models.CheckConstraint(condition=models.Q(('amount_lcy__gte', 0)), name='portfolioincome_amount_lcy_gte_zero'),
        ),
    ]
