services:
  docs:
    image: money_tracker_local_docs
    container_name: money_tracker_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./money_tracker:/app/money_tracker:z
    ports:
      - '9000:9000'
    command: /start-docs
