volumes:
  money_tracker_local_postgres_data: {}
  money_tracker_local_postgres_data_backups: {}
  money_tracker_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: money_tracker_local_django
    container_name: money_tracker_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: money_tracker_production_postgres
    container_name: money_tracker_local_postgres
    volumes:
      - money_tracker_local_postgres_data:/var/lib/postgresql/data
      - money_tracker_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: money_tracker_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: money_tracker_local_redis
    
    volumes:
      - money_tracker_local_redis_data:/data
    
  celeryworker:
    <<: *django
    image: money_tracker_local_celeryworker
    container_name: money_tracker_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    user: "1000:1000" 
    ports: []
    command: /start-celeryworker
    environment:
      - CELERY_WORKER_LOGLEVEL=info
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  celerybeat:
    <<: *django
    image: money_tracker_local_celerybeat
    container_name: money_tracker_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat
    environment:
      - CELERY_BEAT_LOGLEVEL=info
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  flower:
    <<: *django
    image: money_tracker_local_flower
    container_name: money_tracker_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  react:
    build: 
      context: ../../frontend/
      dockerfile: Dockerfile.dev
    image: money_tracker_local_react
    container_name: money_tracker_local_react
    depends_on:
      - django
    volumes:
      - ../../frontend:/app
    ports:
      - '5173:5173'

