# Generated by Django 5.2.2 on 2025-06-25 14:48

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Currency code must be 3 uppercase letters.')])),
                ('description', models.CharField(max_length=100)),
                ('is_local', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ccreator', related_query_name='ccreator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cmodifier', related_query_name='cmodifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Exchange rate against the local currency in two decimal places.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ercreator', related_query_name='ercreator', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates', related_query_name='exchange_rate', to='currencies.currency')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ermodifier', related_query_name='ermodifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_local'], name='currencies__is_loca_ecdcb7_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['code'], name='currencies__code_712bc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_local', True)), fields=('is_local',), name='unique_local_currency'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['currency'], name='currencies__currenc_55685b_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['rate'], name='currencies__rate_62a87f_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(condition=models.Q(('created_at__date', django.db.models.functions.datetime.TruncDate('created_at'))), fields=('currency',), name='unique_currency_per_day'),
        ),
    ]
