# Generated by Django 5.2.2 on 2025-07-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='is_current',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
