# Generated by Django 5.2.2 on 2025-10-20 17:59

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ccreator', related_query_name='ccreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currency',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cmodifier', related_query_name='cmodifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ercreator', related_query_name='ercreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates', related_query_name='exchange_rate', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ermodifier', related_query_name='ermodifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_local'], name='currencies__is_loca_ecdcb7_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['code'], name='currencies__code_712bc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_local', True)), fields=('is_local',), name='unique_local_currency'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['currency'], name='currencies__currenc_55685b_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['rate'], name='currencies__rate_62a87f_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(condition=models.Q(('created_at__date', django.db.models.functions.datetime.TruncDate('created_at'))), fields=('currency',), name='unique_currency_per_day'),
        ),
    ]
