# Generated by Django 5.2.2 on 2025-07-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_exchangerate_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='ISO 4217 currency code (e.g. KES, USD)', max_length=3, primary_key=True, serialize=False),
        ),
    ]
