# Generated by Django 5.2.2 on 2025-07-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_alter_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='is_local',
            field=models.BooleanField(default=False, help_text='Is this the local currency?'),
        ),
    ]
