# Generated by Django 5.2.2 on 2025-07-20 15:43

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="User's Phone Number", max_length=128, null=True, region=None),
        ),
    ]
